name: ESLint & Prettier Check

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run-code-integrity-check:
    uses: ./.github/workflows/code-integrity-check.yml
    secrets: inherit

  build-project:
    runs-on: ubuntu-latest
    needs: run-code-integrity-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: npm run build
