name: Build Develop Branch

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run-code-integrity-check:
    uses: ./.github/workflows/code-integrity-check.yml
    secrets: inherit

  build-project:
    runs-on: ubuntu-latest
    needs: run-code-integrity-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
